### ISSUE TITLE
Crash it no focus on startup

### ISSUE THREAD

**Issue by searles** [searles/FractviewAndroid#14]
This bug should receive move attention because it is responsible for the majority of remaining crashes! To reproduce, clear cache of the app, start it and immediately switch.

How to solve in a clean way: 

* The splash screen should be bound to the MainActivity, ie, the main activity decides when to show it. 
* Keep in mind, that a bitmap fragment might be activated any time, theoretically with a different drawer that always takes some time for initialization. 
* Thus, when a bitmap fragment is created, its initialization code should run in the background.
    + During initialization, there is no interaction between others.
    + For each bitmap fragment, initialization happens exactly once in the beginning when the drawer is created.
* This leads to the following clean way:
    + BitmapFragment contains a method 'isInitializing()' that returns true if initialization is starting. A viewer can react to this and display a periodic message with a waiting wheel plus avoid any interaction. isInitializing must be true after start-up. It may only change to false once in the entire lifetime of the bitmap fragment!
        - Advantage: If the MainActivity is destroyed, it is no big deal.
    + BitmapFragmentListeners are informed when the initialization is done. This call must happen in the UI-Thread.
    + In viewer's on-create, if the attached fragment is busy, two components are added centered right after the viewer registered with the bitmap fragment.

About calling things from the ui thread: https://stackoverflow.com/questions/13974661/runonuithread-vs-looper-getmainlooper-post-in-android.

For Toast messages, use DialogHelper and check whether app has focus. If not, ignore Toasts.

~~~
05-27 01:06:18.213 4814-4814/at.searles.fractview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: at.searles.fractview, PID: 4814
                                                                    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
                                                                        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
                                                                        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
                                                                        at android.app.BackStackRecord.commit(BackStackRecord.java:672)
                                                                        at android.app.DialogFragment.show(DialogFragment.java:230)
                                                                        at at.searles.fractview.BitmapFragment$2$1.run(BitmapFragment.java:283)
~~~

**Comment by searles** [comment]
Almost done. Only thing missing is a mechanism to show a message on top of image. Start init message should be shown inside the new bitmapfragmentview.

**Comment by searles** [comment]
Fixed by adding an Init-Plugin to BitmapFragment.
