### ISSUE TITLE
Crash due to bad integer in Beta 55

### ISSUE THREAD

**Issue by searles** [searles/FractviewAndroid#18]
java.lang.NumberFormatException: 
  at java.lang.Integer.parseInt(Integer.java:524)
  at java.lang.Integer.parseInt(Integer.java:556)
  at at.searles.meelan.Syntax$2.apply(Syntax.java:36)

**Comment by searles** [comment]
Fix by changing integer-Regex to maximum 8 digits. Line 148 in Syntax.java.
