### ISSUE TITLE
Fix crash: Toast in setSizeUnsafe

### ISSUE THREAD

**Issue by searles** [searles/FractviewAndroid#4]
Stack trace:

java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done(AsyncTask.java:309)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: 
  at android.os.Handler.<init>(Handler.java:200)
  at android.os.Handler.<init>(Handler.java:114)
  at android.widget.Toast$TN.<init>(Toast.java:348)
  at android.widget.Toast.<init>(Toast.java:104)
  at android.widget.Toast.makeText(Toast.java:262)
  at at.searles.fractview.BitmapFragment.setSizeUnsafe(Unknown Source:0)
  at at.searles.fractview.BitmapFragment.-wrap0(Unknown Source:0)
  at at.searles.fractview.BitmapFragment$3.run(Unknown Source:0)
  at at.searles.fractview.BitmapFragment$6.doInBackground(Unknown Source:0)
  at at.searles.fractview.BitmapFragment$6.doInBackground(Unknown Source:0)

**Comment by searles** [comment]
Replace all toasts by calls to DialogHelper.
